linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - dupl
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - gocyclo
    - golint
    - gosec
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
